version: '3.8'

services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-db
    ports:
      - "1521:1521"   # Oracle listener
    network_mode: bridge
    environment:
      ORACLE_PASSWORD: Oracle123  # Contraseña para SYSTEM/SYS
    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./sql:/container-entrypoint-initdb.d  # Monta scripts de inicialización
    restart: unless-stopped

volumes:
  oracle-data: